### ISSUE TITLE
Positive Affirmation Command

### ISSUE THREAD

**Issue by Likey00** [rosalogia/rucs24-bot#23]
### Specify what type of functionality your request pertains to

- [X] Command
- [ ] Other

### Describe how it should work

Someone types !affirmation, and a positive affirmation is outputted

#### [Optionally] Describe a potential solution

Simple api call to the url affirmations.dev can return one :)

**Comment by rosalogia** [comment]
@jessicakara this is pretty similar to what you implemented with the joke command; do you want to try taking this one?

**Comment by Poppamunz** [comment]
I can try this one, I wanna give this a go
