### ISSUE TITLE
[FEATURE] Currency Conversion Command

### ISSUE THREAD

**Issue by rosalogia** [rosalogia/rucs24-bot#58]
### Specify what type of functionality your request pertains to

- [x] Command
- [ ] Other

### Describe how it should work

A command that takes in a source and target currency as well as a numerical value to convert from the source to the target. E.g.

`!cconvert USD EUR 50`

to which the response might be an embed looking something like this

![image](https://user-images.githubusercontent.com/66163965/95643316-7fb93a00-0a7c-11eb-8a12-03aa974de08b.png)

#### [Optionally] Describe a potential solution

This can be implemented using the [Exchange Rates API](https://exchangeratesapi.io/)

**Comment by Poppamunz** [comment]
i'll try this one

**Comment by rosalogia** [comment]
Closed by #75
