### ISSUE TITLE
[FEATURE] Whois Command

### ISSUE THREAD

**Issue by rosalogia** [rosalogia/rucs24-bot#62]
### Specify what type of functionality your request pertains to

- [x] Command
- [ ] Other

### Describe how it should work

Command to get some basic profile information about a user, such as their profile picture, their join-date, their roles, etc.

**Comment by rzmk** [comment]
Implemented as of #69. However some additional features and fixes might be nice, such as:

- Changing displayed timezone for all displayed times from UTC to US-East
- Displaying a user's current level based on expcog
- Allowing for a user to only type "whois" and output that user's own details
- Fix footer formatting by removing first "at" and make "Today" lowercase
- List roles in descending order, from highest rank to lowest rank
- Send an error message when given not mentioning a user, or giving an invalid input

**Comment by rosalogia** [comment]
Closed for now
